name: TestNCP
main: me.asofold.bpl.testncp.TestNCP
version: 1.4.0
depend:
- NoCheatPlus
commands:
  testncp:
    usage: "/testncp ... reload | input (player) ... | input * | velocity (amount) | noviolations"